  
services:
  php82:
    build:
      context: ./php82
      dockerfile: Dockerfile
    container_name: php82
    ports:
      - 8001:8001
      - 8002:8002
    volumes:
      - ./www/php82:/app
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    ports:
      - "${MAILPIT_PORT_1:-1089}:1025"
      - "${MAILPIT_PORT_2:-8089}:8025"

  reverse:
    build:
      context: ./reverse
      dockerfile: Dockerfile
    container_name: reverse
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
